# Generated by Django 4.1.7 on 2023-03-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
